/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modo_grafico_formulario;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static modo_grafico_formulario.Formulario2.modelo;

/**
 *
 * @author C.andres
 */
public class Formulario3 extends javax.swing.JFrame {
Connection conn = null;
   Statement stmt = null;
    Object[] filas;
    /**
     * Creates new form Registro
     */
    public Formulario3() {
        initComponents();
        ImageIcon fondo = new ImageIcon("src/gris.jpg");
        Icon icono = new ImageIcon(fondo.getImage().getScaledInstance(lblfondo3.getWidth(), lblfondo3.getHeight(), Image.SCALE_DEFAULT));
        lblfondo3.setIcon(icono);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Boton_amarillo = new javax.swing.JButton();
        Boton_verde = new javax.swing.JButton();
        Boton_rojo = new javax.swing.JButton();
        jtfUsuario = new javax.swing.JTextField();
        lblfondo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Datos Ingresados");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Encontrados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        tabla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Primer Nombre", "Segundo nombre", "Primer Apellido", "Segundo Apellido", "Direccion", "Telefono", "email", "Tipo de documento", "Numero de documento", "Genero"
            }
        ));
        tabla.setOpaque(false);
        jScrollPane2.setViewportView(tabla);

        Boton_amarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/siguiente.png"))); // NOI18N
        Boton_amarillo.setText("Eliminar Registro");
        Boton_amarillo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_amarilloActionPerformed(evt);
            }
        });

        Boton_verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ace.png"))); // NOI18N
        Boton_verde.setText("Realizar Consulta");
        Boton_verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_verdeActionPerformed(evt);
            }
        });

        Boton_rojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/can.png"))); // NOI18N
        Boton_rojo.setText("Salir");
        Boton_rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_rojoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1056, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(Boton_verde)
                .addGap(18, 18, 18)
                .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Boton_amarillo)
                .addGap(124, 124, 124)
                .addComponent(Boton_rojo)
                .addGap(169, 169, 169))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_rojo)
                    .addComponent(Boton_amarillo)
                    .addComponent(Boton_verde)
                    .addComponent(jtfUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 59, 1100, 390));
        getContentPane().add(lblfondo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_verdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_verdeActionPerformed
        
       Select();
    }//GEN-LAST:event_Boton_verdeActionPerformed

    private void Boton_rojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_rojoActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Boton_rojoActionPerformed

    private void Boton_amarilloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_amarilloActionPerformed
        Delete();
    }//GEN-LAST:event_Boton_amarilloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //Formulario3 app = new Formulario3();
       // app.Delete(cli_nombre);
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario3().setVisible(true);
            }
        });
    }

    
    
    
    
    
   /* public void Delete(String cli_nombre ){
     conectar con= new conectar();
        Connection reg=con.conexion();
        String sql = "DELETE FROM cliente WHERE cli_nombre like '%"+jtfUsuario.getText()+"%'";
        try{
        PreparedStatement pstmt = conn.prepareStatement(sql);
        pstmt.setString(1, cli_nombre);
         pstmt.executeUpdate();
          
        JOptionPane.showMessageDialog(null, "Estos son los datos encontrados.");
       //error de lectura a los campos de la bd
            
      
      } catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error sql no se pueden leer datos");
          //error desconocido //por lo general no hay conexion con la base de datos
        }
      
      
       
    }*/
     
    
     void Delete(){
        conectar con= new conectar();
        Connection reg=con.conexion();
         String Consulta = ("Delete from cliente where cli_nombre like '%"+jtfUsuario.getText()+"%'");
        Statement Comando;
        
        try {
            Comando = reg.createStatement();
            Comando.executeUpdate(Consulta);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e.getMessage());
             JOptionPane.showMessageDialog(null, "NO se pudo");
        }
        
    }
    
    
    
    
public void Select(){
      try{
          
            conectar con= new conectar();
        Connection reg=con.conexion();
        JOptionPane.showMessageDialog(null, "Estos son los datos encontrados.");
         /* Formulario3 fdr2 = new Formulario3();
          fdr2.setVisible(true);
          fdr2.setLocationRelativeTo(null);*/
        
        //Creo la consulta SQL
        Statement consulta=(Statement) reg.createStatement();                                   //textField de busqueda
        ResultSet rs = consulta.executeQuery("select * from cliente where cli_nombre like '%"+jtfUsuario.getText()+"%'");
        //Reasigno un modelo en blanco:
        modelo = new DefaultTableModel();//creamos la columnas de nuestra tabla:
                 modelo.addColumn("Primer Nombre");
                 modelo.addColumn("Segundo NOmbre");
                 modelo.addColumn("Primer Apellido");
                 modelo.addColumn("Segundo Apellido");
                 modelo.addColumn("Direccion");
                 modelo.addColumn("telefono");
                 modelo.addColumn("email");
                 modelo.addColumn("tipo documento");
                 modelo.addColumn("numero documento");
                 modelo.addColumn("genero");
            //asigno el tamaÃ±o del arreglo co la cantidad de columnas:
                 filas = new Object[modelo.getColumnCount()];
            //escribo las filas:
            while (rs.next())
            {                   //cantidad de columnas
                 for (int i=0;i<modelo.getColumnCount();i++){
                  filas[i] = rs.getObject(i+1);
                 }
                 //escribo las filas del resultado SQL//
                 modelo.addRow(filas);
                 tabla.setModel(modelo);
            }
              //error de lectura a los campos de la bd
              } catch(SQLException e){
            JOptionPane.showMessageDialog(null,"Error sql no se pueden leer datos");
          //error desconocido //por lo general no hay conexion con la base de datos
        }
      
       
    }
 private void captura(){
        JOptionPane.showMessageDialog(null, "Estos son los datos encontrados.");
          Formulario2 fdr = new Formulario2();
          fdr.setVisible(true);
          fdr.setLocationRelativeTo(null);
        
     }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_amarillo;
    private javax.swing.JButton Boton_rojo;
    private javax.swing.JButton Boton_verde;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jtfUsuario;
    private javax.swing.JLabel lblfondo3;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
